server:
  port: 8091
  #前端响应时间
  tomcat:
    connection-timeout: 65000
spring:
  redis:
    host: 192.168.75.128
    port: 6379
    database: 0
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0
  #后端响应时间
  mvc:
    async:
      request-timeout: 60000
  datasource:
    url: jdbc:mysql:///jtadmin?characterEncoding=utf-8&serverTimezone=Asia/Shanghai   #修改为你使用的库名
    username: root
    password: root
  thymeleaf:
    cache: true
    prefix: classpath:/templates/
    suffix: .html
mybatis-plus:
  type-aliases-package: com.feng.pojo
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
